baseURL                = "https://yuroucelinexiao.github.io/celines-stealth-creamery/"
locale                 = "en-us"
title                  = "Celine's Stealth Creamery"
theme                  = "hugo-theme-stack"
defaultContentLanguage = "en"
hasCJKLanguage         = false

[params]
    # Tell the theme to load your custom CSS
    customCSS = ["css/custom.css"]
    # Configure search to use summaries instead of full content
    [params.search]
        useSummary = true

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
