[en]
    title  = "Celine's Stealth Creamery"
    weight = 1
    languageCode = "en-us"

    [en.params]
        label  = "English"

    [en.params.sidebar]
        subtitle = "Documenting every pint on the Ninja CREAMi Deluxe journey"
