mainSections   = ["post"]
rssFullContent = true
favicon        = "/favicon.svg"

[footer]
    since = 2026

[sidebar]
    subtitle = "Celine's Stealth Creamery"
    avatar   = "img/avatar.png"

[article]

[widgets]
    homepage = [
        { type = "search" },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page     = [{ type = "toc" }]